version: '3'
services:
  mariadb_cs_pm1:
    image: alphatoxic/mcs:latest
    depends_on:
      - mariadb_cs_um
      - mariadb_cs_pm2
    environment:
      - MARIADB_CS_UM_SERVICE_HOST=${MARIADB_CS_UM_SERVICE_HOST}
      - MARIADB_CS_PM1_SERVICE_HOST=${MARIADB_CS_PM1_SERVICE_HOST}
      - MARIADB_CS_PM2_SERVICE_HOST=${MARIADB_CS_PM2_SERVICE_HOST}
    expose:
      - 3306
      - 8606
    container_name: pm1
    command: ./entrypoint.sh
    networks:
      app_net:
        ipv4_address: ${MARIADB_CS_PM1_SERVICE_HOST}

  mariadb_cs_um:
    image: alphatoxic/mcs:latest
    expose:
      - 3306
      - 22
      - 8606
    ports:
      - "4306:3306"
    command: /usr/sbin/sshd -D
    container_name: um
    networks:
      app_net:
        ipv4_address: ${MARIADB_CS_UM_SERVICE_HOST}

  mariadb_cs_pm2:
    image: alphatoxic/mcs:latest
    expose:
      - 3306
      - 22
      - 8606
    command: /usr/sbin/sshd -D
    container_name: pm2
    networks:
      app_net:
        ipv4_address: ${MARIADB_CS_PM2_SERVICE_HOST}

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET}
